#define TAPPING_TERM 150
// #define POINTING_DEVICE_MOTION_PIN GP24
// #define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW
#define POINTING_DEVICE_CS_PIN GP25
#define POINTING_DEVICE_SCLK_PIN GP26
#define POINTING_DEVICE_SDIO_PIN GP27
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
